### ISSUE TITLE
Serious vanilla problem- Can't place crafting bench.

### ISSUE THREAD

**Issue by drachenchunter** [SeriousCreeper/SeriousVanilla-1.10.2#1]
Whenever I try to place a crafting bench it disappears.
Tried placing it on grass it disappears, as well as on spruce logs
Placed on marble they turn into  spruce wood planks.
as well as on stone.

I'm making them out of spruce as that is the trees I've found.
tried placing a JACB crafting bench and it had the same problem.

Will try seing what the portable crafting bench does when I've made it.

**Comment by SeriousCreeper** [comment]
Hm i can't reproduce this, they seem to place just fine for me (both vanilla ones and JACB ones). 

Are you on a server?
Are you using the latest version of the pack? 
Did you add any mods or made any other modifications?
Does it still happen if you restart the game, or try it in a new world?

**Comment by drachenchunter** [comment]
Local game. SSP. 
It's the latest one on the curse launcher.  
Didn't change a thing.
Literally just started using it. so it's a new world. will create another one to see.
did set the world creation to have a bonus chest.

**Comment by drachenchunter** [comment]
creating a new world didn't fix it. But restarted the game and it seems to be working.  
Tried that first but whatever.

**Comment by SeriousCreeper** [comment]
Very strange! let me know when it happens again :)
