### ISSUE TITLE
stuck in bed after sleeping

### ISSUE THREAD

**Issue by mdinnocenzo** [SeriousCreeper/SeriousVanilla-1.10.2#2]
Found that after sleeping it doesn't bring you back to a standing position.  You are stuck in the sleeping screen next to the bed.

Local game, no additional mods or changes to modpack.
[2016-11-04-4.log.gz](https://github.com/Kiyaku/SeriousVanilla-1.10.2/files/572980/2016-11-04-4.log.gz)

**Comment by SeriousCreeper** [comment]
Unfortunately that's a bug in 1.10.2, nothing i can do about, it's minecraft itself, not any mod causing it :/
